name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b45cd607fc8e38dc047a563edccf78804d7f1603de1a017fc60b4e9239e8828"

[versions]
forge = "47.3.27"
minecraft = "1.20.1"
