name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4434261bd885fc3f696794afdfdb88b6ae4e99a564e2d68bbf06d1903859a63b"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
