name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07df4e7778073e8fefc164c541e24ed864e81e5611ac3786d60106bac8392f2b"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
