name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ca24728dcf1a8de69e22b75bd51785125a6b4669511123ad1baadb6f5a50dd4"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
