name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07796776f2e8feacd53a376ed02e97ec3cd089c97aef028359afc8b737792ce7"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
