name = "MrModpackisen"
author = "RavenHamster"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92b2fd927c968bf117132c040e3e72a225231c93f6d8dd2b63fb59d7d992d746"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
